### ISSUE TITLE
When sampling many digital inputs the response in occasionally garbled

### ISSUE THREAD

**Issue by captbilly** [Tenkiv/Tekdaqc-Firmware#133]
When sampling all digital inputs (with or without analog sampling) we get an occasional garbled digital input response (perhaps one sample out of 20).  The response will be missing about half of the normal data (it could be beginning, middle or end, anywhere in the message), so timestamp or channel or part of each could be missing.  The error occurs whether using putty or the Tekdaqc manager software.

**Comment by ejberry** [comment]
Fixed as of 1.2.0.0
