### ISSUE TITLE
Read_Analog_input --Input=all command does not return correct result

### ISSUE THREAD

**Issue by captbilly** [Tenkiv/Tekdaqc-Firmware#161]
When using the Read_Analog_input --Input=all command the Tekdaqc returns only the temperature sensor reading and not the other added channels.  If I use the Read_Analog_Input --Input=0-3 (with those channels added) I get the added channels plus the temperature sensor reading.

**Comment by pchiacha** [comment]
fixed as of v1.4.1.0
