### ISSUE TITLE
Adding a redundant input causes temperature reference to stop sampling

### ISSUE THREAD

**Issue by ejberry** [Tenkiv/Tekdaqc-Firmware#164]
Steps to reproduce.
Connect to board.
Send following commands in quick succession.

> SET_ANALOG_INPUT_SCALE --SCALE=ANALOG_SCALE_5V
SET_DIGITAL_OUTPUT --OUTPUT=0000
SAMPLE --NUMBER=0
ADD_ANALOG_INPUT --INPUT=0 --GAIN=1 --RATE=2.5 --BUFFER=ENABLED
ADD_ANALOG_INPUT --INPUT=1 --GAIN=1 --RATE=2.5 --BUFFER=ENABLED
ADD_ANALOG_INPUT --INPUT=0 --GAIN=1 --RATE=2.5 --BUFFER=ENABLED

Tekdaqc will sample inputs 0 and 1 but not temperature reference. Can be reproduced by using any redundant input even the temperature reference.

This bug doesn't seem to occur if all inputs have already been sampled and goes away after calling the sample command a second time.

**Comment by pchiacha** [comment]
updated in v1.4.1.0
