### ISSUE TITLE
Add modify channel commands

### ISSUE THREAD

**Issue by jwoolston** [Tenkiv/Tekdaqc-Firmware#66]
_Issue by **[jwoolston](https://github.com/jwoolston)** from Saturday Dec 21, 2013 at 01:25 GMT_
_Originally opened as https://github.com/Tenkiv/TekDAQC_Firmware_Old/issues/66_

---

Related to #65 
- Analog Input
- Digital Input
- Digital Output

Should allow for the modification of all or some of the parameters for these channels.

**Comment by pchiacha** [comment]
as of v1.3.0.0:
analog input can be modified through add_analog_input command

as of v1.11.0.0 :
there is no parameter to modify when adding and removing digital input (no changes made)
digital output can already be modified (no changes made)
