### ISSUE TITLE
Make command parser more generic

### ISSUE THREAD

**Issue by jwoolston** [Tenkiv/Tekdaqc-Firmware#98]
_Issue by **[jwoolston](https://github.com/jwoolston)** from Wednesday Feb 19, 2014 at 03:49 GMT_
_Originally opened as https://github.com/Tenkiv/TekDAQC_Firmware_Old/issues/98_

---

Should be able to handle any command interface such as usb, ethernet, CAN, etc.

**Comment by ejberry** [comment]
Impossible on this hardware revision.
